"""empty message

Revision ID: 88079249570c
Revises: c9543c4467a8
Create Date: 2022-05-20 14:34:38.091406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88079249570c'
down_revision = 'c9543c4467a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
